CREATE TABLE IF NOT EXISTS erp_work_order_sync (
  work_order_id BIGINT UNSIGNED NOT NULL,
  erp_prod_header_id BIGINT UNSIGNED NOT NULL,
  erp_agenda_id BIGINT UNSIGNED NOT NULL,
  erp_worker_ot_id BIGINT UNSIGNED NULL,
  erp_worker_init_id BIGINT UNSIGNED NULL,
  erp_worker_id BIGINT UNSIGNED NULL,
  erp_worker_name VARCHAR(160) NULL,
  erp_user_id BIGINT UNSIGNED NULL,
  erp_user_login VARCHAR(120) NULL,
  erp_prod_number VARCHAR(80) NOT NULL,
  erp_req_id VARCHAR(80) NULL,
  erp_plan_desc VARCHAR(255) NULL,
  erp_plan_date VARCHAR(40) NULL,
  erp_plan_timestamp BIGINT NULL,
  erp_machine_id BIGINT NULL,
  erp_machine_label VARCHAR(120) NULL,
  erp_machine_type_id BIGINT NULL,
  erp_planta_id BIGINT NULL,
  erp_target_qty DECIMAL(12,3) NULL,
  erp_header_status VARCHAR(40) NULL,
  erp_agenda_status VARCHAR(40) NULL,
  erp_agenda_active TINYINT(1) NOT NULL DEFAULT 0,
  erp_worker_status VARCHAR(40) NULL,
  last_synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (work_order_id),
  UNIQUE KEY uq_erp_work_order_sync_agenda (erp_agenda_id),
  UNIQUE KEY uq_erp_work_order_sync_header_agenda (erp_prod_header_id, erp_agenda_id),
  KEY idx_erp_work_order_sync_prod_number (erp_prod_number),
  KEY idx_erp_work_order_sync_plan_ts (erp_plan_timestamp),
  CONSTRAINT fk_erp_work_order_sync_wo FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
